/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nora;

import java.util.List;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class ListTutorials extends javax.swing.JPanel {
    private List<Tutorial> allTutorials;
    
    
    /**
     * Creates new form ListTutorials
     */
    public ListTutorials() {
        initComponents();
        
        fillTutorialsTable();        
    }
    
    public void setSelectedTutorial(int totId){
        int rowId = 1;
        for(int i=0;i<allTutorials.size();i++){
            if(allTutorials.get(i).getId() == totId){
                rowId = i;
            }
        }
        tableTutorials.setRowSelectionInterval(rowId, rowId);
    }
    
    public void fillTutorialsTable(){
        DB db = new DB();
        allTutorials = db.getAllTutorials();
        Object[][] rows = new Object[allTutorials.size()][3];
        
        for(int i =0;i< allTutorials.size();i++){
            Object[] row = new Object[5];
            row[0] = allTutorials.get(i).getId();
            row[1] = allTutorials.get(i).getTitle();
            row[2] = db.getUsername(allTutorials.get(i).getUser_id());
            rows[i] = row;
        }
        
        String[] titles = {"Id","Title","User","Number Of Questions"};
        
        tableTutorials.setModel(new javax.swing.table.DefaultTableModel(
            rows,
            titles
        ));
        tableTutorials.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tableTutorials.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(e.getValueIsAdjusting())
                    return;
                
                int selectedIndex = ((DefaultListSelectionModel) e.getSource()).getAnchorSelectionIndex();
                selectedTutorialPane.setViewportView(new TutorialPanel(allTutorials.get(selectedIndex)));

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTutorials = new javax.swing.JTable();
        selectedTutorialPane = new javax.swing.JScrollPane();

        tableTutorials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tableTutorials.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableTutorials);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectedTutorialPane)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedTutorialPane, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane selectedTutorialPane;
    private javax.swing.JTable tableTutorials;
    // End of variables declaration//GEN-END:variables
}
