/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nora;

import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        AskQuestionPanel askQuestionPanel = new AskQuestionPanel();
        //ListTutorials listTutorialsPanel = new ListTutorials();
        MyProfilePanel myProfilePanel = new MyProfilePanel();
        BoardPanel boardPanel = new BoardPanel();
        
        
        
        jTabbedPane1.addTab("Ask Question", askQuestionPanel);
        jTabbedPane1.addTab("Answer Question", new AnswerQuestionPanel());
        jTabbedPane1.addTab("New tutorial", new PostTutorialPanel());
        jTabbedPane1.addTab("My Profile", myProfilePanel);
        jTabbedPane1.addTab("Board", boardPanel);
        
        
        jTabbedPane1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                myProfilePanel.fillAllTables();
            }
        });
        
        myProfilePanel.setTutorialSelectionChangeListener((Tutorial t) -> {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
            boardPanel.setTutorial(t);
        });
        
        myProfilePanel.setQuestionSelectionChangeListener((Question q) -> {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
            boardPanel.setQuestion(q);
        });
        
        myProfilePanel.setAnswerSelectionChangeListener((Answer a) -> {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
            DB db = new DB();
            boardPanel.setQuestion(db.getQuestionForAnswer(a));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
